server:
  port: 8071

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.113.122.84:3306/speedlogisticsdb
    username: root
    password: 12345

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

debug: true

logging:
  level:
    com.zero.logistics.dao: debug