server:
  port: 8071

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/speedlogisticsdb
    username: root
    password: 12345

mybatis:
  mapper-locations: classpath:mapper/*.xml